export const productAction = {
  FETCH_PRODUCTS: () => "FETCH_PRODUCTS",
  FETCH_CATEGORIES: () => "FETCH_CATEGORIES",
  FETCH_BRANDS: () => "FETCH_BRANDS",
  ADD_TO_CART: () => "ADD_TO_CART",
  UPDATE_TO_CART: () => "UPDATE_TO_CART",
  REMOVE_FROM_CART: () => "REMOVE_FROM_CART",
  SET_CATEGORY: () => "SET_CATEGORY",
  SET_BRAND: () => "SET_BRAND",
};
